### ISSUE TITLE
[LiveDisplay] Random kernel panics

### ISSUE THREAD

**Issue by dreamwhite** [crdroidandroid/android_device_oneplus_fajita#1]
Hi there,
sorry if this isn't the right place where to ask but I'm having a problem with my OnePlus 6T (fajita) on crDroid 7.4 build (29 mar official from Terminator_J).

Before giving the logs I'll try to write a small introduction:

when LiveDisplay is enabled (Settings/Display/LiveDisplay/DisplayMode/Automatic), randomly the system panics (reboots or freezes). I don't know how to reproduce this kind of behaviour, but mos of the time it happened while using Amazon Prime Video (is this even related?). When the system freezes, if I was watching a video, the playing audio changes to a static frequency sound.

Despite what I wrote above, I did a few tests with LiveDisplay disabled, but I'm still experiencing this weird bug.

Below the extracted logs using `adb logcat -b all > logcat.txt`

[logcat.txt.zip](https://github.com/crdroidandroid/android_device_oneplus_fajita/files/6290185/logcat.txt.zip)

Many thanks for your patience and your time and sorry again if I wrote wrongly in this repo

**Comment by gwolf2u** [comment]
please ask support related questions on device specific forum or telegram (see support button)
https://crdroid.net/fajita

**Comment by dreamwhite** [comment]
> please ask support related questions on device specific forum or telegram (see support button)
> https://crdroid.net/fajita

Oh sorry, I opened an issue there since I was suggested to write there. I'll ask support on XDA thread then :)
